name: FermiBadger_env
channels:
  - conda-forge
dependencies:
  - badger-opt=1.6.0
  - python=3.12.1
  - pip:
      - cpymad==1.19.0
      - xcoll==0.11.1
      - xdeps==0.10.19
      - xfields==0.25.18
      - xobjects==0.6.4
      - xpart==0.23.13
      - xsuite==0.54.0
      - xtrack==0.107.0
      - --extra-index-url https://www-bd.fnal.gov/pip3 
      - acsys==0.12.8

