name: FermiBadger_env
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - annotated-types=0.7.0
  - backports.zstd=1.6.0
  - badger-opt=1.6.0
  - botorch=0.17.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.6.17
  - cairo=1.18.4
  - certifi=2026.6.17
  - cffi=2.0.0
  - charset-normalizer=3.4.7
  - colorama=0.4.6
  - contourpy=1.3.3
  - coolname=5.0.0
  - cpython=3.12.13
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - deap=1.4.4
  - filelock=3.29.4
  - fmt=12.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.18.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.63.0
  - freetype=2.14.3
  - fribidi=1.0.16
  - fsspec=2026.6.0
  - gest-api>=0.2
  - glib=2.88.1
  - glib-tools=2.88.1
  - gmp=6.3.0
  - gmpy2=2.3.0
  - gpytorch=1.15.2
  - graphite2=1.3.15
  - gst-plugins-base=1.26.11
  - gstreamer=1.26.11
  - h2=4.3.0
  - harfbuzz=14.2.1
  - hpack=4.2.0
  - hyperframe=6.1.0
  - icu=78.3
  - idna=3.18
  - jaxtyping=0.3.11
  - jinja2=3.1.6
  - joblib=1.5.3
  - kiwisolver=1.5.0
  - krb5=1.22.2
  - lcms2=2.19.1
  - lerc=4.1.0
  - libabseil=20260526.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang-cpp18.1=18.1.8
  - libclang-cpp22.1=22.1.8
  - libclang13=22.1.8
  - libcxx=22.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.8.1
  - libffi=3.5.2
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.88.1
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.4.1
  - liblapack=3.11.0
  - libllvm18=18.1.8
  - libllvm22=22.1.8
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.33
  - libopus=1.6.1
  - libpng=1.6.58
  - libpq=18.4
  - libprotobuf=7.35.1
  - libraqm=0.10.5
  - libsqlite=3.53.2
  - libtiff=4.7.1
  - libtorch=2.12.1
  - libuv=1.52.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.3
  - libxml2-16=2.15.3
  - libzlib=1.3.2
  - linear_operator=0.6.1
  - llvm-openmp=22.1.8
  - markupsafe=3.0.3
  - matplotlib-base=3.11.0
  - mpc=1.4.0
  - mpfr=4.2.2
  - mpmath=1.3.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - narwhals=2.22.1
  - ncurses=6.6
  - networkx=3.6.1
  - nomkl=1.0
  - nspr=4.38
  - nss=3.118
  - numpy=2.5.0
  - onednn=3.12
  - openjpeg=2.5.4
  - openldap=2.6.13
  - openssl=3.6.3
  - opt_einsum=3.4.0
  - optree=0.19.1
  - orjson=3.11.9
  - packaging=26.2
  - pandas=3.0.3
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.2.0
  - pip=26.1.2
  - pixman=0.46.4
  - platformdirs=4.10.0
  - ply=3.11
  - pthread-stubs=0.4
  - pybind11=3.0.3
  - pybind11-abi=11
  - pybind11-global=3.0.3
  - pycparser=3.0
  - pydantic=2.13.4
  - pydantic-core=2.46.4
  - pyparsing=3.3.2
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqtgraph=0.14.0
  - pyre-extensions=0.0.32
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - python=3.12.1
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.13
  - python-moocore=0.3.1
  - python_abi=3.12
  - pytorch=2.12.1
  - pyyaml=6.0.3
  - qdarkstyle=3.2.3
  - qhull=2020.2
  - qt-main=5.15.15
  - qtpy=2.4.3
  - readline=8.3
  - requests=2.34.2
  - scikit-learn=1.9.0
  - scipy=1.18.0
  - setuptools=81.0.0
  - sip=6.15.3
  - six=1.17.0
  - sleef=3.9.0
  - sympy=1.14.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.4.1
  - tqdm=4.68.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - tzdata=2025c
  - unicodedata2=17.0.1
  - urllib3=2.7.0
  - wadler-lindig=0.1.7
  - wheel=0.47.0
  - xopt>=3.2.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - yaml=0.2.5
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - cpymad==1.19.0
      - cython==3.2.6
      - decorator==5.3.1
      - gssapi==1.11.1
      - lark==1.3.1
      - meson==1.11.1
      - minrpc==0.2.0
      - nest-asyncio==1.6.0
      - ruamel-yaml==0.19.1
      - xcoll==0.11.1
      - xdeps==0.10.19
      - xfields==0.25.18
      - xobjects==0.6.4
      - xpart==0.23.13
      - xsuite==0.54.0
      - xtrack==0.107.0
      - --extra-index-url https://www-bd.fnal.gov/pip3 
      - acsys==0.12.8

